#define EXPRESSION_SIZE 61
#define MAX_OPERATION_NUMBERS 20

#define VALID_YES_SIZE 2
#define VALID_NO_SIZE 2
#define VALID_OPERATIONS_SIZE 8

extern const char VALID_YES[VALID_YES_SIZE];

extern const char VALID_NO[VALID_NO_SIZE];

extern const char VALID_OPERATIONS[VALID_OPERATIONS_SIZE];
